import fs from "node:fs";

const app=fs.readFileSync(new URL("../public/app.js",import.meta.url),"utf8");
const admin=fs.readFileSync(new URL("../public/admin.js",import.meta.url),"utf8");
const worker=fs.readFileSync(new URL("../src/index.js",import.meta.url),"utf8");
const html=fs.readFileSync(new URL("../public/admin.html",import.meta.url),"utf8");
const storefront=fs.readFileSync(new URL("../public/index.html",import.meta.url),"utf8");
const guide=fs.readFileSync(new URL("../public/guide.html",import.meta.url),"utf8");
const i18n=fs.readFileSync(new URL("../public/i18n.js",import.meta.url),"utf8");
const wrangler=fs.readFileSync(new URL("../wrangler.jsonc",import.meta.url),"utf8");
const receipt=fs.readFileSync(new URL("../public/receipt.js",import.meta.url),"utf8");

const checks={
  checkoutHandler:/async function checkout\(event\)/.test(app),
  checkoutEndpoint:/path==="\/api\/orders"&&request\.method==="POST"/.test(worker),
  stockValidation:/insufficient_stock/.test(worker),
  safeSubmitButton:/event\.submitter\|\|form\.querySelector/.test(app),
  clickableTracking:/function trackingLink\(order/.test(app)&&/target="_blank"/.test(app),
  printableReceipt:/data-print-receipt-paper/.test(app)&&/JIGZReceipt/.test(app)&&/window\.print\(\)/.test(receipt),
  orderTimeline:/function timelineHtml\(order\)/.test(app),
  trackingShare:/navigator\.share/.test(app)&&/data-copy-tracking/.test(app),
  codCloseGuard:/cod_payment_required/.test(worker)&&/cod-received/.test(worker),
  adminAppointment:/\/api\/admin\/staff/.test(worker),
  ownerProductDelete:/request\.method==="DELETE"/.test(worker)&&/owner_required/.test(worker),
  categoryDropdown:/function categoryOptions/.test(admin)&&/newCategory/.test(admin),
  directProductUpload:/function productImageData/.test(admin)&&/function productImageUploader/.test(admin)&&/type="file"/.test(admin),
  fifoOpeningCost:/unitCost/.test(admin)&&/inventory_lots/.test(worker),
  editableAgents:/function editAgent/.test(admin)&&/UPDATE_AGENT/.test(worker),
  editableCommissions:/function editCommission/.test(admin)&&/UPDATE_COMMISSION/.test(worker),
  promotionImage:/promoImage/.test(admin)&&/normalizedImages\(body\.image/.test(worker),
  selectProductWorks:/"scrollProducts" in target\.dataset/.test(app),
  themedNavIcons:/<svg viewBox="0 0 24 24"/.test(storefront),
  cartStarAnimation:/function flyStarToCart/.test(app)&&/Math\.random/.test(app)&&/cart-star/.test(app),
  jigzWarpCartEffect:/jigz-cart-flight/.test(app)&&/jigz-warp-burst/.test(app)&&/jigz-cart-impact/.test(app)&&/navigator\.vibrate/.test(app),
  customOrderSound:/function playAlertSound/.test(admin)&&/setSoundFile/.test(admin)&&/notification_sound/.test(worker),
  promotionManagement:/UPDATE_PROMOTION/.test(worker)&&/DELETE_PROMOTION/.test(worker)&&/function editPromotion/.test(admin),
  reportFilters:/reportFilterForm/.test(admin)&&/url\.searchParams\.get\("from"\)/.test(worker),
  checkoutLayout:/checkout-form/.test(app)&&/checkout-section/.test(app)&&/ยอดชำระทั้งหมด/.test(app),
  qrDownload:/function downloadQrImage/.test(app)&&/data-download-qr/.test(app),
  bankCopy:/function copyBankNumber/.test(app)&&/data-copy-bank/.test(app),
  walletSchema:/CREATE TABLE IF NOT EXISTS wallet_accounts/.test(worker)&&/CREATE TABLE IF NOT EXISTS wallet_transactions/.test(worker)&&/prevent_negative_wallet_balance/.test(worker),
  walletCustomerApi:/path==="\/api\/wallet"/.test(worker)&&/\/api\/wallet\/deposits/.test(worker)&&/\/api\/wallet\/withdrawals/.test(worker),
  walletCustomerUi:/function showWallet\(/.test(app)&&/function showWalletDeposit/.test(app)&&/function showWalletWithdrawal/.test(app),
  easySlipV2:/https:\/\/api\.easyslip\.com\/v2\/verify\/bank/.test(worker)&&/EASYSLIP_API_KEY/.test(worker),
  slipSafety:/matchAccount:true/.test(worker)&&/matchAmount:expectedAmount/.test(worker)&&/checkDuplicate:true/.test(worker),
  walletAdmin:/id="wallet" class="page"/.test(html)&&/function loadWalletRequests/.test(admin)&&/function reviewWallet/.test(admin),
  agentWalletLink:/id="agentUserId"/.test(html)&&/userId:\$\("#agentUserId"\)\.value/.test(admin)&&/idx_agents_user/.test(worker),
  commissionWalletRelease:/function releaseWeeklyCommissions/.test(worker)&&/\/api\/admin\/commissions\/release/.test(worker)&&/'COMMISSION','CREDIT'/.test(worker),
  weeklyCron:/"0 10 \* \* SUN"/.test(wrangler)&&/async scheduled\(/.test(worker),
  financeIdempotency:/idx_wallet_reference/.test(worker)&&/idx_slip_trans_ref/.test(worker),
  closingSchema:/CREATE TABLE IF NOT EXISTS financial_closings/.test(worker)&&/UNIQUE\(period_type,period_key\)/.test(worker),
  closingApi:/\/api\/admin\/closings/.test(worker)&&/function calculateClosing/.test(worker)&&/function createClosing/.test(worker),
  closingUi:/id="closings" class="page"/.test(html)&&/function loadClosings/.test(admin)&&/function createFinancialClosing/.test(admin)&&/function showClosingDetail/.test(admin),
  closingTransactionList:/function closingTransactions/.test(worker)&&/item_summary/.test(worker)&&/id="closingTransactionRows"/.test(html)&&/function renderClosingTransactions/.test(admin),
  closingTransactionSnapshot:/transactions:preview\.transactions/.test(worker)&&/Snapshot ที่ปิดแล้ว/.test(admin)&&/data-order-detail/.test(admin),
  ownerOrderInfoEdit:/function updateOrderInfo/.test(worker)&&/UPDATE_ORDER_INFO/.test(worker)&&/order_edit_reason_required/.test(worker)&&/data-order-info-edit/.test(admin)&&/function editOrderInfo/.test(admin),
  customerPaymentDeliverySplit:/function showCheckoutPaymentDelivery/.test(app)&&/id="checkoutDelivery"/.test(app)&&/cod-deposit-proof/.test(worker)&&/cod_deposit_amount/.test(worker)&&/VERIFY_COD_DEPOSIT/.test(worker)&&/data-upload-cod-deposit/.test(app),
  ownerSlipReviewAndRiderShipping:/slip-review/.test(worker)&&/REVIEW_ORDER_SLIP/.test(worker)&&/data-slip-review/.test(admin)&&/shippingDeliveryMethod/.test(admin)&&/deliveryDueAmount/.test(admin),
  ownerFullOrderEdit:/function updateOrderFull/.test(worker)&&/UPDATE_ORDER_FULL/.test(worker)&&/data-full-item-qty/.test(admin)&&/orderInfoPayment/.test(admin)&&/orderInfoStatus/.test(admin),
  settingsFallback:/\.settings\|\|\{\}/.test(app)&&/shopName:state\.settings\.shop_name\|\|"JIGᶻ AGENT"/.test(app),
  safeApiCollections:/const safeArray=value=>Array\.isArray\(value\)\?value:\[\]/.test(app)&&/state\.products=safeArray/.test(app)&&/state\.orders=safeArray/.test(app)&&/safeArray\(order\.items\)\.map/.test(app),
  safeAdminCollections:/function safeArray\(value\)\{return Array\.isArray\(value\)\?value:\[\]\}/.test(admin)&&/state\.products=safeArray/.test(admin)&&/state\.orders=safeArray/.test(admin)&&/safeArray\(order\.items\)\.map/.test(admin),
  thaiClosingBoundary:/7\*3600000/.test(worker)&&/period_type/.test(worker),
  safeUserDelete:/userDeleteMatch/.test(worker)&&/ARCHIVE_USER/.test(worker)&&/user_balance_not_zero/.test(worker)&&/user_wallet_pending/.test(worker),
  userDeleteUi:/data-user-delete/.test(admin)&&/function deleteUser/.test(admin),
  primaryOwnerSchema:/is_primary_owner/.test(worker)&&/idx_single_primary_owner/.test(worker),
  secondaryOwnerLimit:/secondary_owner_limit/.test(worker)&&/limit_secondary_owners_update/.test(worker)&&/secondaryOwnerLimit:4/.test(worker),
  ownerApprovalFlow:/owner_deletion_requests/.test(worker)&&/REQUEST_OWNER_DELETION/.test(worker)&&/APPROVE_OWNER_DELETION/.test(worker)&&/primary_owner_required/.test(worker),
  ownerUi:/secondaryOwnerCount/.test(html)&&/function renderOwnerRequests/.test(admin)&&/function reviewOwnerDeletion/.test(admin),
  calmMotion:/calm-star-drift/.test(fs.readFileSync(new URL("../public/enhancements.css",import.meta.url),"utf8"))&&/prefers-reduced-motion/.test(fs.readFileSync(new URL("../public/enhancements.css",import.meta.url),"utf8")),
  responsiveSafeArea:/safe-area-inset/.test(fs.readFileSync(new URL("../public/enhancements.css",import.meta.url),"utf8"))&&/100dvh/.test(fs.readFileSync(new URL("../public/enhancements.css",import.meta.url),"utf8")),
  labeledProductForm:/class="field-label"/.test(admin)&&/ราคาขายต่อ 1 หน่วย/.test(admin)&&/สต็อกเริ่มต้น/.test(admin),
  standardPriceTiers:/ใช้เรท 1G–1000G/.test(admin)&&/10,30,50,100,500,1000/.test(admin)&&/function readPriceTiers/.test(admin),
  customerRateMenu:/function sizeLabel/.test(app)&&/product-rate-list/.test(app)&&/เลือกขนาด \/ เรทราคา/.test(app),
  stockAwareTierMenu:/function reservedQuantity/.test(app)&&/สต็อกไม่พอ/.test(app)&&/data-cart-qty/.test(app)&&/function stockProblem/.test(app),
  aggregateStockGuard:/requestedByProduct/.test(worker)&&/fifoReservations/.test(worker)&&/prevent_negative_product_stock/.test(worker),
  checkoutStockRefresh:/กำลังตรวจสอบสต็อก/.test(app)&&/await loadProducts\(\);const problem=stockProblem/.test(app),
  safeOrderDelete:/deleted_at/.test(worker)&&/order_delete_requires_closed/.test(worker)&&/DELETE_ORDER/.test(worker)&&/actor\.role!=="OWNER"/.test(worker),
  orderDeleteUi:/function deleteOrder/.test(admin)&&/data-order-delete/.test(admin)&&/order-delete-button/.test(admin),
  contextualCreateActions:/data-action="create-pos"/.test(html)&&/data-action="focus-staff"/.test(html)&&/data-action="focus-agent"/.test(html)&&/data-action="focus-promotion"/.test(html),
  deletedOrderRestoresStock:/DELETE_RETURN/.test(worker)&&/stock_returned_at/.test(worker)&&/deleted_by_name/.test(worker),
  weeklyStockCount:/inventory_counts/.test(worker)&&/WEEKLY_STOCK_COUNT/.test(worker)&&/function weeklyStockCount/.test(admin),
  customerStylePos:/pos-customer-grid/.test(html)&&/pos-product-card/.test(admin),
  posDirectQuantity:/data-pos-product-qty/.test(admin)&&/data-pos-qty-input/.test(admin)&&/function setPosQuantity/.test(admin)&&/function posMaxQty/.test(admin),
  posPerBillPrice:/data-pos-price-input/.test(admin)&&/function setPosPrice/.test(admin)&&/salePrice/.test(admin)&&/hasPosOverride=source==="POS"/.test(worker)&&/posPriceOverrides/.test(worker),
  posCodShipping:/id="posShipping"/.test(html)&&/id="posCodAmount"/.test(html)&&/function updatePosTotals/.test(admin)&&/shippingFee:totals\.shipping/.test(admin)&&/codAmount/.test(worker)&&/invalid_cod_amount/.test(worker),
  adminGetRetry:/attempts=method==="GET"\?2:1/.test(admin)&&/setTimeout\(resolve,350\)/.test(admin),
  fastHealth:/function quickHealth/.test(worker)&&/health_timeout/.test(worker)&&/"run_worker_first": true/.test(wrangler),
  adminGateTimeout:/AbortSignal\.timeout/.test(admin)&&/เวลานานกว่าปกติ/.test(admin),
  packingRollback:/data-order-rollback/.test(admin)&&/function rollbackPacking/.test(admin)&&/ROLLBACK_PACKING_STATUS/.test(worker)&&/rollback_reason_required/.test(worker),
  linkedSalesAutoCommission:/function applyPosSalesAgent/.test(admin)&&/salesAgent/.test(admin)&&/agent_type='SALES'/.test(worker)&&/autoSalesAgent/.test(worker)&&/commissionCreated/.test(worker),
  salesSelfWorkspace:/id="my-sales" class="page"/.test(html)&&/function loadMySales/.test(admin)&&/\/api\/admin\/sales\/me/.test(worker)&&/function salesWorkspace/.test(worker)&&/WHERE user_id=\? AND agent_type='SALES'/.test(worker),
  salesPermissionBoundary:/effectiveRole/.test(worker)&&/sales_permission_denied/.test(worker)&&/classList\.add\("sales-mode"\)/.test(admin),
  posPriceApproval:/function posPriceApprovalQuote/.test(worker)&&/APPROVE_POS_PRICE/.test(worker)&&/sales_max_discount_percent/.test(worker)&&/setSalesMinMargin/.test(html),
  commissionStatement:/function printMySalesStatement/.test(admin)&&/COMMISSION STATEMENT/.test(admin)&&/print-my-sales/.test(html),
  paidCommissionReversal:/COMMISSION_REVERSAL/.test(worker)&&/COMMISSION_OFFSET/.test(worker)&&/offsetTotal/.test(worker),
  fullSystemSettings:/PUBLIC_SETTING_KEYS/.test(worker)&&/hero_title/.test(worker)&&/enable_transfer/.test(worker)&&/setMinimumOrder/.test(html),
  profileAvatar:/avatar_image/.test(worker)&&/profileAvatarFile/.test(app)&&/applyProfileHeader/.test(app),
  rewardSystem:/CREATE TABLE IF NOT EXISTS rewards/.test(worker)&&/REDEEM_REWARD/.test(worker)&&/id="rewards" class="page"/.test(html)&&/function showRewards/.test(app),
  customerGuide:/href="\/guide\.html"/.test(storefront)&&/คู่มือการใช้งานเว็บไซต์/.test(guide)&&/id="tracking"/.test(guide),
  languageSwitcher:/data-language-select/.test(storefront)&&/data-language-select/.test(html)&&/data-language-select/.test(guide),
  threeLanguages:/SUPPORTED=\["th","en","zh"\]/.test(i18n)&&/JIGZI18N/.test(i18n),
  preservesSpecificData:/data-i18n-skip/.test(storefront)&&/data-i18n-skip/.test(app),
  localizedFormatting:/Intl\.NumberFormat\(locale/.test(app)&&/toLocaleString\(locale\)/.test(admin),
  accessJwtValidation:/cf-access-jwt-assertion/.test(worker)&&/crypto\.subtle\.verify/.test(worker)&&/POLICY_AUD/.test(worker),
  orderIdempotency:/CREATE TABLE IF NOT EXISTS order_idempotency/.test(worker)&&/idempotencyKey/.test(app)&&/invalid_idempotency_key/.test(worker),
  timedReservation:/reservation_expires_at/.test(worker)&&/cleanupExpiredReservations/.test(worker)&&/"\*\/5 \* \* \* \*"/.test(wrangler),
  immutableAudit:/audit_logs_no_update/.test(worker)&&/audit_log_immutable/.test(worker),
  systemAlerts:/CREATE TABLE IF NOT EXISTS system_alerts/.test(worker)&&/SLIP_REVIEW/.test(worker)&&/LOW_STOCK/.test(worker),
  dualApproval:/CREATE TABLE IF NOT EXISTS approval_requests/.test(worker)&&/APPROVE_WITHDRAWAL/.test(worker)&&/reviewHighRiskApproval/.test(admin),
  backupExport:/path==="\/api\/admin\/backup"/.test(worker)&&/jigz-backup-/.test(worker),
  healthCenter:/id="health" class="page"/.test(html)&&/function loadSystemHealth/.test(admin)&&/\/api\/admin\/system-health/.test(worker),
  complianceGate:/compliance_required/.test(worker)&&/checkoutCompliance/.test(app)&&/compliance_text/.test(worker),
  reservationProofHold:/reservation_expires_at=CASE WHEN \?='VERIFIED'/.test(worker),
  internalAdminAccess:/CREATE TABLE IF NOT EXISTS admin_access_requests/.test(worker)&&/DEVICE_APPROVAL/.test(worker)&&/data-access-review/.test(admin)&&/gateRequest/.test(html),
  googleVerification:/googlea735a29242109529\.html/.test(worker)&&/google-site-verification: googlea735a29242109529\.html/.test(worker)&&/"run_worker_first": true/.test(wrangler),
  searchDiscovery:/pathname==="\/sitemap\.xml"/.test(worker)&&/application\/xml/.test(worker)&&/pathname==="\/robots\.txt"/.test(worker)&&/Disallow: \/admin/.test(worker)&&/"run_worker_first": true/.test(wrangler),
  noAccessHealthWarning:!/ACTION_REQUIRED/.test(worker)&&!/Cloudflare Access/.test(admin),
  orderDateFilters:/id="orderFrom"/.test(html)&&/id="orderTo"/.test(html)&&/id="orderPayment"/.test(html)&&/id="orderSource"/.test(html)&&/date\(created_at,'\+7 hours'\)/.test(worker)&&/filters=\{q:/.test(admin),
  largeDataFilters:/id="productCategoryFilter"/.test(html)&&/id="customerOnlineFilter"/.test(html)&&/id="agentSearchFilter"/.test(html)&&/id="commissionFrom"/.test(html)&&/id="promotionStatusFilter"/.test(html)&&/function renderUsers/.test(admin)&&/function renderAgentTables/.test(admin)&&/function renderPromotions/.test(admin),
  walletDateSearch:/id="walletSearchFilter"/.test(html)&&/id="walletFrom"/.test(html)&&/id="walletTo"/.test(html)&&/date\(r\.created_at,'\+7 hours'\)/.test(worker),
  responsiveDataFilters:/data-filters/.test(fs.readFileSync(new URL("../public/admin.css",import.meta.url),"utf8"))&&/filter-summary/.test(fs.readFileSync(new URL("../public/admin.css",import.meta.url),"utf8")),
  mobileTableCards:/function labelResponsiveTables/.test(admin)&&/data-label/.test(fs.readFileSync(new URL("../public/admin.css",import.meta.url),"utf8")),
  mobilePosCart:/id="posCartToggle"/.test(html)&&/id="posCartPanel"/.test(html)&&/function togglePosCart/.test(admin)&&/pos-cart-open/.test(fs.readFileSync(new URL("../public/admin.css",import.meta.url),"utf8")),
  searchMetadata:/rel="canonical"/.test(storefront)&&/og:title/.test(storefront)&&/twitter:card/.test(storefront)&&/application\/ld\+json/.test(storefront)&&/"@type":"OnlineStore"/.test(storefront),
  peopleFirstSeo:/ร้านค้าปลีกสมุนไพรและสินค้าออนไลน์/.test(storefront)&&/class="seo-content"/.test(storefront)&&/function shareStoreLink/.test(app),
  distinctPaidCompleted:/status-colors\.css/.test(html)&&/status-PAID/.test(fs.readFileSync(new URL("../public/status-colors.css",import.meta.url),"utf8"))&&/status-COMPLETED/.test(fs.readFileSync(new URL("../public/status-colors.css",import.meta.url),"utf8")),
  allOrderStatusColors:["NEW","ACCEPTED","PENDING_PAYMENT","PAID","PACKING","PACKED","SHIPPED","COMPLETED","CANCELLED"].every(value=>fs.readFileSync(new URL("../public/status-colors.css",import.meta.url),"utf8").includes(`status-${value}`)),
  storeCredit:/credit_accounts/.test(worker)&&/credit_transactions/.test(worker)&&/creditCodeHash/.test(worker)&&/id="creditAccountForm"/.test(html)&&/checkoutCreditCode/.test(app),
  posCredit:/id="posCreditAccount"/.test(html)&&/id="posCreditAmount"/.test(html)&&/api\/admin\/credit-options/.test(worker)&&/credit-settled/.test(worker)&&/CREDIT_OVERDUE/.test(worker)&&/function loadPosCreditOptions/.test(admin),
  actualShippingCost:/id="actualShippingCost"/.test(admin)&&/id="fulfillmentExpense"/.test(admin)&&/actual_shipping_cost/.test(worker)&&/fulfillment_expense/.test(worker)&&/shipping_cost_recorded_by/.test(worker)&&/invalid_actual_shipping_cost/.test(worker)&&/totals\.shippingCost/.test(admin),
  sampleCostTracking:/data-pos-sample/.test(admin)&&/is_sample/.test(worker)&&/line\.isSample\?"SAMPLE":"SALE"/.test(worker)&&/ตัวเทส\/ของแถม/.test(admin),
  productVariants:/product_variants/.test(worker)&&/variantConfig/.test(worker)&&/id="productVariant"/.test(app)&&/product-variant-editor/.test(admin)&&/id="receiveVariant"/.test(html),
  riderPayment:/enable_rider/.test(worker)&&/payment_channel/.test(worker)&&/value="RIDER"/.test(html)&&/value="RIDER"/.test(app),
  linkedAgentWithoutCode:/autoSalesAgent/.test(worker)&&/linkedSalesAgent/.test(worker)&&/state\.agent/.test(app),
  slipBindCount:/VALUES\(\?,'ORDER',\?,'EASYSLIP',\?,\?,\?,\?,\?,\?,\?,\?\)/.test(worker)&&/VALUES\(\?, 'DEPOSIT',\?,'EASYSLIP',\?,\?,\?,\?,\?,\?,\?,\?\)/.test(worker),
  productionReceipt:/window\.JIGZReceipt/.test(receipt)&&/@page\{size:/.test(receipt)&&/paper==="58"/.test(receipt)&&/paper==="80"/.test(receipt)&&/data-print-receipt-paper="58"/.test(admin)&&/data-print-receipt-paper="A4"/.test(app),
  receiptPrivacy:!/actual_cost|actual_shipping_cost|fulfillment_expense/.test(receipt),
  systemVersion:/version:"5\.17\.0"/.test(worker)&&/v5\.17\.0/.test(html)
};

if(Object.values(checks).some(value=>!value))throw new Error(`feature_check_failed:${JSON.stringify(checks)}`);
console.log(JSON.stringify({ok:true,checks}));
