import seedCatalog from "../public/products.json";

const JSON_HEADERS={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const enc=new TextEncoder();
const ADMIN_ROLES=new Set(["OWNER","ADMIN"]);
const ORDER_STATUSES=new Set(["NEW","ACCEPTED","PENDING_PAYMENT","PAID","PACKING","PACKED","SHIPPED","COMPLETED","CANCELLED"]);
const NEXT_STATUS={NEW:["ACCEPTED","CANCELLED"],ACCEPTED:["PACKING","CANCELLED"],PENDING_PAYMENT:["PAID","CANCELLED"],PAID:["PACKING","CANCELLED"],PACKING:["PACKED","CANCELLED"],PACKED:["SHIPPED","CANCELLED"],SHIPPED:["COMPLETED"],COMPLETED:[],CANCELLED:[]};

function json(data,init={}){return new Response(JSON.stringify(data),{...init,headers:{...JSON_HEADERS,...(init.headers||{})}})}
function b64(bytes){let s="";for(const byte of bytes)s+=String.fromCharCode(byte);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")}
function fromB64(value){const normalized=value.replaceAll("-","+").replaceAll("_","/");const raw=atob(normalized+"=".repeat((4-normalized.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
function b64json(value){return b64(enc.encode(JSON.stringify(value)))}
function clean(value,max=200){return String(value??"").trim().slice(0,max)}
function number(value,min=0,max=1e9){const n=Number(value);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function sameOrigin(request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin}
function requireOrigin(request){return sameOrigin(request)?null:json({error:"invalid_origin"},{status:403})}
function randomToken(){const bytes=new Uint8Array(32);crypto.getRandomValues(bytes);return b64(bytes)}
function orderId(){const d=new Date(),date=`${String(d.getUTCFullYear()).slice(-2)}${String(d.getUTCMonth()+1).padStart(2,"0")}${String(d.getUTCDate()).padStart(2,"0")}`,suffix=crypto.randomUUID().replaceAll("-","").slice(0,8).toUpperCase();return`OD${date}-${suffix}`}
function sessionCookie(token){return`jigz_sid=${encodeURIComponent(token)}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=31536000`}
function readCookie(request){const match=(request.headers.get("cookie")||"").match(/(?:^|;\s*)jigz_sid=([^;]+)/);return match?decodeURIComponent(match[1]):""}
async function digest(value){return new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(value)))}
async function tokenHash(token){return b64(await digest(token))}
async function parseBody(request){const type=request.headers.get("content-type")||"";if(!type.includes("application/json"))throw new Error("invalid_content_type");const length=Number(request.headers.get("content-length")||0);if(length>800000)throw new Error("payload_too_large");return request.json()}

async function initializeDatabase(db){
 await db.exec(`
 CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,name TEXT NOT NULL,brand TEXT NOT NULL DEFAULT 'JIGz',category TEXT NOT NULL,unit TEXT NOT NULL,price REAL,prices_json TEXT NOT NULL DEFAULT '{}',stock REAL,images_json TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_products_status_category ON products(status,category,name);
 CREATE TABLE IF NOT EXISTS inventory_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id TEXT NOT NULL,movement_type TEXT NOT NULL,quantity REAL NOT NULL,note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE TABLE IF NOT EXISTS inventory_lots(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id TEXT NOT NULL,received_qty REAL NOT NULL,remaining_qty REAL NOT NULL,unit_cost REAL NOT NULL,supplier TEXT,note TEXT,received_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE INDEX IF NOT EXISTS idx_lots_fifo ON inventory_lots(product_id,remaining_qty,received_at,id);
 CREATE TRIGGER IF NOT EXISTS prevent_negative_product_stock BEFORE UPDATE OF stock ON products WHEN NEW.stock < 0 BEGIN SELECT RAISE(ABORT,'insufficient_stock'); END;
 CREATE TRIGGER IF NOT EXISTS prevent_negative_lot_stock BEFORE UPDATE OF remaining_qty ON inventory_lots WHEN NEW.remaining_qty < 0 BEGIN SELECT RAISE(ABORT,'insufficient_lot_stock'); END;
 CREATE TABLE IF NOT EXISTS agents(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,name TEXT NOT NULL,agent_type TEXT NOT NULL CHECK(agent_type IN ('RESELLER','SALES')),commission_rate REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,display_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('CUSTOMER','ADMIN','OWNER')),status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_users_role_seen ON users(role,last_seen_at);
 CREATE TABLE IF NOT EXISTS user_sessions(token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE INDEX IF NOT EXISTS idx_sessions_user ON user_sessions(user_id,expires_at);
 CREATE TABLE IF NOT EXISTS user_profiles(user_id TEXT PRIMARY KEY,full_name TEXT,phone TEXT,address TEXT,points REAL NOT NULL DEFAULT 0,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE TABLE IF NOT EXISTS sales_orders(id TEXT PRIMARY KEY,user_id TEXT,source TEXT NOT NULL CHECK(source IN ('ONLINE','POS')),customer_name TEXT NOT NULL,phone TEXT,address TEXT,agent_code TEXT,payment_method TEXT NOT NULL CHECK(payment_method IN ('TRANSFER','COD','CASH')),status TEXT NOT NULL,subtotal REAL NOT NULL,discount REAL NOT NULL DEFAULT 0,shipping_fee REAL NOT NULL DEFAULT 0,total REAL NOT NULL,note TEXT,payment_proof TEXT,tracking_company TEXT,tracking_number TEXT,created_by TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,paid_at TEXT,shipped_at TEXT,completed_at TEXT,cancelled_at TEXT,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(agent_code) REFERENCES agents(code));
 CREATE INDEX IF NOT EXISTS idx_sales_orders_status_created ON sales_orders(status,created_at);
 CREATE INDEX IF NOT EXISTS idx_sales_orders_user_created ON sales_orders(user_id,created_at);
 CREATE TABLE IF NOT EXISTS sales_order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL,product_id TEXT NOT NULL,product_name TEXT NOT NULL,unit TEXT NOT NULL,pack_size REAL NOT NULL,pack_qty REAL NOT NULL,quantity REAL NOT NULL,unit_price REAL NOT NULL,line_total REAL NOT NULL,actual_cost REAL NOT NULL DEFAULT 0,FOREIGN KEY(order_id) REFERENCES sales_orders(id),FOREIGN KEY(product_id) REFERENCES products(id));
 CREATE INDEX IF NOT EXISTS idx_sales_items_order ON sales_order_items(order_id);
 CREATE TABLE IF NOT EXISTS sales_commissions(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id TEXT NOT NULL UNIQUE,agent_id INTEGER NOT NULL,revenue_net REAL NOT NULL,actual_cost REAL NOT NULL,deductions REAL NOT NULL,profit_base REAL NOT NULL,commission_rate REAL NOT NULL,commission_amount REAL NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',approved_at TEXT,paid_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(order_id) REFERENCES sales_orders(id),FOREIGN KEY(agent_id) REFERENCES agents(id));
 CREATE INDEX IF NOT EXISTS idx_sales_commission_agent_status ON sales_commissions(agent_id,status,created_at);
 CREATE TABLE IF NOT EXISTS points_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,order_id TEXT,type TEXT NOT NULL,points REAL NOT NULL,reason TEXT,actor_id TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE UNIQUE INDEX IF NOT EXISTS idx_points_order_type ON points_ledger(order_id,type) WHERE order_id IS NOT NULL;
 CREATE INDEX IF NOT EXISTS idx_points_user_created ON points_ledger(user_id,created_at);
 CREATE TABLE IF NOT EXISTS promotions(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT,discount_type TEXT NOT NULL DEFAULT 'INFO',discount_value REAL NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'ACTIVE',starts_at TEXT,ends_at TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS chat_messages(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,display_name TEXT NOT NULL,message TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE INDEX IF NOT EXISTS idx_chat_created ON chat_messages(created_at,id);
 CREATE TABLE IF NOT EXISTS audit_logs(id INTEGER PRIMARY KEY AUTOINCREMENT,actor_id TEXT,action TEXT NOT NULL,entity_type TEXT NOT NULL,entity_id TEXT,details_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at,id);
 CREATE TABLE IF NOT EXISTS system_settings(setting_key TEXT PRIMARY KEY,setting_value TEXT NOT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
 CREATE TABLE IF NOT EXISTS push_subscriptions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id TEXT NOT NULL,endpoint TEXT NOT NULL UNIQUE,subscription_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'ACTIVE',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));
 CREATE INDEX IF NOT EXISTS idx_push_user_status ON push_subscriptions(user_id,status,updated_at);
 `);
 const defaults={shop_name:"JIGᶻ AGENT Store",announcement:"ระบบออนไลน์ 24 ชั่วโมง",shop_open:"true",shipping_fee:"50",line_oa:"@jigz",instagram:"jigz.agent",bank_name:"",bank_account:"",bank_number:"",qr_image:"",theme:"space",points_rate:"100"};
 await db.batch(Object.entries(defaults).map(([key,value])=>db.prepare("INSERT OR IGNORE INTO system_settings(setting_key,setting_value) VALUES(?,?)").bind(key,value)));
 const count=await db.prepare("SELECT COUNT(*) AS total FROM products").first();
 if(Number(count?.total||0)===0){const insert=db.prepare("INSERT OR IGNORE INTO products(id,name,brand,category,unit,price,prices_json,stock,images_json,status) VALUES(?,?,?,?,?,?,?,?,?,'ACTIVE')");const statements=seedCatalog.products.map(product=>insert.bind(product.id,product.name,product.brand||"JIGz",product.category,product.unit,product.price,JSON.stringify(product.prices||{}),product.stock,JSON.stringify(product.images||[])));for(let i=0;i<statements.length;i+=500)await db.batch(statements.slice(i,i+500))}
}

async function currentUser(request,db){const token=readCookie(request);if(!token)return null;return(await db.prepare("SELECT u.id,u.display_name,u.role,u.status FROM user_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>CURRENT_TIMESTAMP AND u.status='ACTIVE'").bind(await tokenHash(token)).first())||null}
async function newUser(db,role){const id=crypto.randomUUID(),token=randomToken(),hash=await tokenHash(token),expires=new Date(Date.now()+31536000000).toISOString(),displayName=`JIGZ-${id.slice(0,8).toUpperCase()}`;await db.batch([db.prepare("INSERT INTO users(id,display_name,role) VALUES(?,?,?)").bind(id,displayName,role),db.prepare("INSERT INTO user_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)").bind(hash,id,expires),db.prepare("INSERT INTO user_profiles(user_id) VALUES(?)").bind(id)]);return{user:{id,display_name:displayName,role,status:"ACTIVE"},cookie:sessionCookie(token)}}
async function ensureUser(request,db,wantsAdmin=false){await initializeDatabase(db);let user=await currentUser(request,db),cookie="";if(!user){const count=await db.prepare("SELECT COUNT(*) total FROM users WHERE role IN ('OWNER','ADMIN') AND status='ACTIVE'").first(),role=wantsAdmin&&Number(count?.total||0)===0?"OWNER":"CUSTOMER",created=await newUser(db,role);user=created.user;cookie=created.cookie}if(wantsAdmin&&user.role==="CUSTOMER"){const count=await db.prepare("SELECT COUNT(*) total FROM users WHERE role IN ('OWNER','ADMIN') AND status='ACTIVE'").first();if(Number(count?.total||0)===0){await db.prepare("UPDATE users SET role='OWNER',last_seen_at=CURRENT_TIMESTAMP WHERE id=?").bind(user.id).run();user.role="OWNER"}else return{denied:true,user,cookie}}await db.prepare("UPDATE users SET last_seen_at=CURRENT_TIMESTAMP WHERE id=?").bind(user.id).run();return{user,cookie}}
async function audit(db,actor,action,entityType,entityId,details={}){await db.prepare("INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,details_json) VALUES(?,?,?,?,?)").bind(actor?.id||null,action,entityType,entityId||null,JSON.stringify(details)).run()}

function mapProduct(row){return{...row,prices:JSON.parse(row.prices_json||"{}"),images:JSON.parse(row.images_json||"[]"),prices_json:undefined,images_json:undefined}}
async function listProducts(db,includeInactive=false){const result=await db.prepare(`SELECT id,name,brand,category,unit,price,prices_json,stock,images_json,status,updated_at FROM products ${includeInactive?"":"WHERE status='ACTIVE'"} ORDER BY category COLLATE NOCASE,name COLLATE NOCASE`).all();return result.results.map(mapProduct)}
async function settings(db,publicOnly=false){const result=await db.prepare("SELECT setting_key,setting_value FROM system_settings").all(),data=Object.fromEntries(result.results.map(row=>[row.setting_key,row.setting_value]));if(publicOnly){const allowed=["shop_name","announcement","shop_open","shipping_fee","line_oa","instagram","bank_name","bank_account","bank_number","qr_image","theme","points_rate"];return Object.fromEntries(allowed.map(key=>[key,data[key]??""]))}return data}
async function getProfile(db,userId){return(await db.prepare("SELECT full_name,phone,address,points,updated_at FROM user_profiles WHERE user_id=?").bind(userId).first())||{full_name:"",phone:"",address:"",points:0}}
function orderRow(row){return{...row,subtotal:Number(row.subtotal),discount:Number(row.discount),shipping_fee:Number(row.shipping_fee),total:Number(row.total)}}
async function orderDetail(db,id,userId=null){const condition=userId?"id=? AND user_id=?":"id=?",order=await db.prepare(`SELECT * FROM sales_orders WHERE ${condition}`).bind(...(userId?[id,userId]:[id])).first();if(!order)return null;const items=await db.prepare("SELECT product_id,product_name,unit,pack_size,pack_qty,quantity,unit_price,line_total,actual_cost FROM sales_order_items WHERE order_id=? ORDER BY id").bind(id).all();return{...orderRow(order),items:items.results}}

async function fifoCost(db,productId,quantity){const lots=await db.prepare("SELECT id,remaining_qty,unit_cost FROM inventory_lots WHERE product_id=? AND remaining_qty>0 ORDER BY received_at,id LIMIT 200").bind(productId).all();let remaining=quantity,cost=0;const deductions=[];for(const lot of lots.results){if(remaining<=0)break;const take=Math.min(remaining,Number(lot.remaining_qty));if(take>0){deductions.push({id:lot.id,quantity:take});cost+=take*Number(lot.unit_cost);remaining-=take}}return{cost,deductions,uncovered:Math.max(0,remaining)}}
async function createOrder(db,actor,body,source="ONLINE"){
 const customerName=clean(body.customerName||body.fullName,120),phone=clean(body.phone,30),address=clean(body.address,500),note=clean(body.note,500),agentCode=clean(body.agentCode,24).toUpperCase()||null,paymentMethod=clean(body.paymentMethod,20).toUpperCase();
 if(!customerName||!phone||!address||!["TRANSFER","COD","CASH"].includes(paymentMethod))throw new Error("invalid_customer");
 const lines=Array.isArray(body.items)?body.items.slice(0,50):[];if(!lines.length)throw new Error("empty_cart");
 const ids=[...new Set(lines.map(line=>clean(line.productId,80)).filter(Boolean))];if(!ids.length)throw new Error("empty_cart");
 const placeholders=ids.map(()=>"?").join(","),found=await db.prepare(`SELECT id,name,unit,price,prices_json,stock,status FROM products WHERE id IN (${placeholders})`).bind(...ids).all(),byId=new Map(found.results.map(row=>[row.id,row]));
 const prepared=[];let subtotal=0;for(const input of lines){const product=byId.get(clean(input.productId,80));if(!product||product.status!=="ACTIVE")throw new Error("product_unavailable");const packSize=number(input.packSize??1,0.001,100000),packQty=number(input.qty,1,10000);if(packSize===null||packQty===null)throw new Error("invalid_quantity");const prices=JSON.parse(product.prices_json||"{}"),packKey=String(packSize),packPrice=number(prices[packKey]??(packSize===1?product.price:null),0,1e8);if(packPrice===null)throw new Error("invalid_price_tier");const quantity=packSize*packQty;if(product.stock===null||Number(product.stock)<quantity)throw new Error(`insufficient_stock:${product.name}`);const fifo=await fifoCost(db,product.id,quantity),lineTotal=packPrice*packQty;prepared.push({product,packSize,packQty,quantity,unitPrice:packPrice/packSize,lineTotal,actualCost:fifo.cost,deductions:fifo.deductions});subtotal+=lineTotal}
 const publicSettings=await settings(db,true),shippingFee=source==="POS"?0:Number(publicSettings.shipping_fee||0),discount=number(body.discount||0,0,subtotal)||0,total=Math.max(0,subtotal-discount+shippingFee),id=orderId(),status=source==="POS"?"PAID":paymentMethod==="TRANSFER"?"PENDING_PAYMENT":"NEW",userId=source==="ONLINE"?actor.id:(clean(body.userId,80)||null),statements=[];
 statements.push(db.prepare("INSERT INTO sales_orders(id,user_id,source,customer_name,phone,address,agent_code,payment_method,status,subtotal,discount,shipping_fee,total,note,created_by,paid_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CASE WHEN ?='PAID' THEN CURRENT_TIMESTAMP END)").bind(id,userId,source,customerName,phone,address,agentCode,paymentMethod,status,subtotal,discount,shippingFee,total,note,actor.id,status));
 for(const line of prepared){statements.push(db.prepare("INSERT INTO sales_order_items(order_id,product_id,product_name,unit,pack_size,pack_qty,quantity,unit_price,line_total,actual_cost) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,line.product.id,line.product.name,line.product.unit,line.packSize,line.packQty,line.quantity,line.unitPrice,line.lineTotal,line.actualCost));statements.push(db.prepare("UPDATE products SET stock=COALESCE(stock,0)-?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(line.quantity,line.product.id));statements.push(db.prepare("INSERT INTO inventory_movements(product_id,movement_type,quantity,note) VALUES(?,'SALE',?,?)").bind(line.product.id,-line.quantity,`Order ${id}`));for(const deduction of line.deductions)statements.push(db.prepare("UPDATE inventory_lots SET remaining_qty=remaining_qty-? WHERE id=?").bind(deduction.quantity,deduction.id))}
 if(source==="ONLINE")statements.push(db.prepare("INSERT INTO user_profiles(user_id,full_name,phone,address) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET full_name=excluded.full_name,phone=excluded.phone,address=excluded.address,updated_at=CURRENT_TIMESTAMP").bind(actor.id,customerName,phone,address));
 await db.batch(statements);await audit(db,actor,"CREATE_ORDER","ORDER",id,{source,total,status,paymentMethod});return orderDetail(db,id)
}

async function recalculateCommission(db,orderIdValue){const order=await db.prepare("SELECT o.id,o.subtotal,o.discount,o.shipping_fee,o.status,a.id agent_id,a.commission_rate FROM sales_orders o JOIN agents a ON a.code=o.agent_code AND a.status='ACTIVE' WHERE o.id=?").bind(orderIdValue).first();if(!order)return null;const costRow=await db.prepare("SELECT COALESCE(SUM(actual_cost),0) actual_cost FROM sales_order_items WHERE order_id=?").bind(orderIdValue).first(),revenueNet=Math.max(0,Number(order.subtotal)-Number(order.discount)),actualCost=Math.max(0,Number(costRow?.actual_cost||0)),deductions=Math.max(0,Number(order.shipping_fee||0)),profitBase=Math.max(0,revenueNet-actualCost-deductions),reversed=order.status==="CANCELLED",commissionAmount=reversed?0:profitBase*(Number(order.commission_rate)/100),status=reversed?"REVERSED":"PENDING";await db.prepare("INSERT INTO sales_commissions(order_id,agent_id,revenue_net,actual_cost,deductions,profit_base,commission_rate,commission_amount,status) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET agent_id=excluded.agent_id,revenue_net=excluded.revenue_net,actual_cost=excluded.actual_cost,deductions=excluded.deductions,profit_base=excluded.profit_base,commission_rate=excluded.commission_rate,commission_amount=excluded.commission_amount,status=excluded.status,approved_at=NULL,paid_at=NULL").bind(orderIdValue,order.agent_id,revenueNet,actualCost,deductions,profitBase,Number(order.commission_rate),commissionAmount,status).run();return{orderId:orderIdValue,revenueNet,actualCost,deductions,profitBase,rate:Number(order.commission_rate),amount:commissionAmount,status}}
async function transitionOrder(db,actor,id,next,extra={}){const order=await db.prepare("SELECT * FROM sales_orders WHERE id=?").bind(id).first();if(!order)throw new Error("order_not_found");next=clean(next,30).toUpperCase();if(!ORDER_STATUSES.has(next)||!NEXT_STATUS[order.status]?.includes(next))throw new Error("invalid_transition");const statements=[];if(next==="CANCELLED"){const items=await db.prepare("SELECT product_id,quantity,actual_cost FROM sales_order_items WHERE order_id=?").bind(id).all();for(const item of items.results){statements.push(db.prepare("UPDATE products SET stock=COALESCE(stock,0)+?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.quantity,item.product_id));statements.push(db.prepare("INSERT INTO inventory_movements(product_id,movement_type,quantity,note) VALUES(?,'CANCEL_RETURN',?,?)").bind(item.product_id,item.quantity,`Cancelled ${id}`));statements.push(db.prepare("INSERT INTO inventory_lots(product_id,received_qty,remaining_qty,unit_cost,note) VALUES(?,?,?,?,?)").bind(item.product_id,item.quantity,item.quantity,Number(item.actual_cost)/Math.max(1,Number(item.quantity)),`Restore ${id}`))}}
 const trackingCompany=clean(extra.trackingCompany,80),trackingNumber=clean(extra.trackingNumber,120);if(next==="SHIPPED"&&(!trackingCompany||!trackingNumber))throw new Error("tracking_required");
 statements.push(db.prepare("UPDATE sales_orders SET status=?,tracking_company=CASE WHEN ?<>'' THEN ? ELSE tracking_company END,tracking_number=CASE WHEN ?<>'' THEN ? ELSE tracking_number END,paid_at=CASE WHEN ?='PAID' THEN COALESCE(paid_at,CURRENT_TIMESTAMP) ELSE paid_at END,shipped_at=CASE WHEN ?='SHIPPED' THEN CURRENT_TIMESTAMP ELSE shipped_at END,completed_at=CASE WHEN ?='COMPLETED' THEN CURRENT_TIMESTAMP ELSE completed_at END,cancelled_at=CASE WHEN ?='CANCELLED' THEN CURRENT_TIMESTAMP ELSE cancelled_at END,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(next,trackingCompany,trackingCompany,trackingNumber,trackingNumber,next,next,next,next,id));await db.batch(statements);
 if(next==="COMPLETED"&&order.user_id){const rateSettings=await settings(db,true),points=Math.floor(Number(order.total)/Math.max(1,Number(rateSettings.points_rate||100)));if(points>0){try{await db.batch([db.prepare("INSERT INTO points_ledger(user_id,order_id,type,points,reason,actor_id) VALUES(?,?,'EARN',?,'ยืนยันรับสินค้า',?)").bind(order.user_id,id,points,actor.id),db.prepare("UPDATE user_profiles SET points=points+?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(points,order.user_id)])}catch(error){if(!String(error).includes("UNIQUE"))throw error}}}
 await recalculateCommission(db,id);await audit(db,actor,"TRANSITION_ORDER","ORDER",id,{from:order.status,to:next,trackingCompany,trackingNumber});return orderDetail(db,id)
}

async function summary(db){const [all,today,pending,packing,shipping,low,agents,commission,online,sales]=await db.batch([db.prepare("SELECT COUNT(*) total FROM sales_orders"),db.prepare("SELECT COUNT(*) total FROM sales_orders WHERE date(created_at)=date('now')"),db.prepare("SELECT COUNT(*) total FROM sales_orders WHERE status='PENDING_PAYMENT'"),db.prepare("SELECT COUNT(*) total FROM sales_orders WHERE status IN ('ACCEPTED','PAID','PACKING')"),db.prepare("SELECT COUNT(*) total FROM sales_orders WHERE status='PACKED'"),db.prepare("SELECT COUNT(*) total FROM products WHERE status='ACTIVE' AND COALESCE(stock,0)<=0"),db.prepare("SELECT COUNT(*) total FROM agents WHERE status='ACTIVE'"),db.prepare("SELECT COALESCE(SUM(commission_amount),0) total FROM sales_commissions WHERE status='PENDING'"),db.prepare("SELECT COUNT(*) total FROM users WHERE last_seen_at>=datetime('now','-5 minutes')"),db.prepare("SELECT COALESCE(SUM(total),0) total FROM sales_orders WHERE date(created_at)=date('now') AND status<>'CANCELLED'")]);return{orders:all.results[0]?.total||0,todayOrders:today.results[0]?.total||0,pending:pending.results[0]?.total||0,packing:packing.results[0]?.total||0,shipping:shipping.results[0]?.total||0,lowStock:low.results[0]?.total||0,activeAgents:agents.results[0]?.total||0,pendingCommission:commission.results[0]?.total||0,onlineUsers:online.results[0]?.total||0,todaySales:sales.results[0]?.total||0}}

async function ensureVapidKeys(db){const existing=await db.prepare("SELECT setting_value FROM system_settings WHERE setting_key='vapid_keys'").first();if(existing?.setting_value)return JSON.parse(existing.setting_value);const pair=await crypto.subtle.generateKey({name:"ECDSA",namedCurve:"P-256"},true,["sign","verify"]),privateJwk=await crypto.subtle.exportKey("jwk",pair.privateKey),publicJwk=await crypto.subtle.exportKey("jwk",pair.publicKey),x=fromB64(publicJwk.x),y=fromB64(publicJwk.y),point=new Uint8Array(65);point[0]=4;point.set(x,1);point.set(y,33);const generated={privateJwk,publicKey:b64(point)};await db.prepare("INSERT OR IGNORE INTO system_settings(setting_key,setting_value) VALUES('vapid_keys',?)").bind(JSON.stringify(generated)).run();const saved=await db.prepare("SELECT setting_value FROM system_settings WHERE setting_key='vapid_keys'").first();return JSON.parse(saved.setting_value)}
async function vapidAuthorization(endpoint,keys){const audience=new URL(endpoint).origin,header=b64json({typ:"JWT",alg:"ES256"}),payload=b64json({aud:audience,exp:Math.floor(Date.now()/1000)+43200,sub:"https://jigz-store.namphujigz.workers.dev"}),unsigned=`${header}.${payload}`,privateKey=await crypto.subtle.importKey("jwk",keys.privateJwk,{name:"ECDSA",namedCurve:"P-256"},false,["sign"]),signature=new Uint8Array(await crypto.subtle.sign({name:"ECDSA",hash:"SHA-256"},privateKey,enc.encode(unsigned)));return`vapid t=${unsigned}.${b64(signature)}, k=${keys.publicKey}`}
async function sendPush(endpoint,keys){try{const response=await fetch(endpoint,{method:"POST",headers:{Authorization:await vapidAuthorization(endpoint,keys),TTL:"60"}});return{ok:response.ok,status:response.status,expired:response.status===404||response.status===410}}catch{return{ok:false,status:0,expired:false}}}
async function notifyAdmins(db){const rows=await db.prepare("SELECT p.id,p.endpoint FROM push_subscriptions p JOIN users u ON u.id=p.user_id WHERE p.status='ACTIVE' AND u.role IN ('OWNER','ADMIN') LIMIT 100").all();if(!rows.results.length)return;const keys=await ensureVapidKeys(db),results=await Promise.all(rows.results.map(async row=>({id:row.id,...await sendPush(row.endpoint,keys)}))),expired=results.filter(item=>item.expired);if(expired.length)await db.batch(expired.map(item=>db.prepare("UPDATE push_subscriptions SET status='EXPIRED',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.id)))}

async function publicApi(request,env,url,user,ctx){const path=url.pathname;
 if(path==="/api/products"&&request.method==="GET")return json({products:await listProducts(env.DB,false)},{headers:{"cache-control":"public, max-age=30, stale-while-revalidate=120"}});
 if(path==="/api/settings/public"&&request.method==="GET")return json({settings:await settings(env.DB,true)});
 if(path==="/api/promotions"&&request.method==="GET"){const result=await env.DB.prepare("SELECT id,title,description,discount_type,discount_value,starts_at,ends_at FROM promotions WHERE status='ACTIVE' AND (starts_at IS NULL OR starts_at<=CURRENT_TIMESTAMP) AND (ends_at IS NULL OR ends_at>=CURRENT_TIMESTAMP) ORDER BY created_at DESC LIMIT 50").all();return json({promotions:result.results})}
 if(path==="/api/profile"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),fullName=clean(body.fullName,120),phone=clean(body.phone,30),address=clean(body.address,500);if(!fullName||!phone||!address)return json({error:"invalid_profile"},{status:400});await env.DB.prepare("INSERT INTO user_profiles(user_id,full_name,phone,address) VALUES(?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET full_name=excluded.full_name,phone=excluded.phone,address=excluded.address,updated_at=CURRENT_TIMESTAMP").bind(user.id,fullName,phone,address).run();return json({ok:true,profile:await getProfile(env.DB,user.id)})}
 if(path==="/api/points"&&request.method==="GET"){const result=await env.DB.prepare("SELECT order_id,type,points,reason,created_at FROM points_ledger WHERE user_id=? ORDER BY id DESC LIMIT 100").bind(user.id).all();return json({points:Number((await getProfile(env.DB,user.id)).points||0),ledger:result.results})}
 if(path==="/api/orders"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;try{const order=await createOrder(env.DB,user,await parseBody(request),"ONLINE");ctx.waitUntil(notifyAdmins(env.DB));return json({ok:true,order},{status:201})}catch(error){const message=error instanceof Error?error.message:"order_failed",status=message.startsWith("insufficient_stock")?409:400;return json({error:message},{status})}}
 if(path==="/api/orders"&&request.method==="GET"){const result=await env.DB.prepare("SELECT id,source,customer_name,payment_method,status,subtotal,discount,shipping_fee,total,tracking_company,tracking_number,created_at,updated_at FROM sales_orders WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(user.id).all();return json({orders:result.results.map(orderRow)})}
 const match=path.match(/^\/api\/orders\/([^/]+)(?:\/(payment-proof|confirm-received))?$/);if(match){const id=decodeURIComponent(match[1]);if(request.method==="GET"&&!match[2]){const detail=await orderDetail(env.DB,id,user.id);return detail?json({order:detail}):json({error:"not_found"},{status:404})}if(request.method==="POST"&&match[2]==="payment-proof"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),proof=clean(body.proof,650000),order=await env.DB.prepare("SELECT status FROM sales_orders WHERE id=? AND user_id=?").bind(id,user.id).first();if(!order)return json({error:"not_found"},{status:404});if(!proof.startsWith("data:image/")||proof.length>650000)return json({error:"invalid_proof"},{status:400});await env.DB.prepare("UPDATE sales_orders SET payment_proof=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(proof,id).run();await audit(env.DB,user,"UPLOAD_PAYMENT_PROOF","ORDER",id);return json({ok:true})}if(request.method==="POST"&&match[2]==="confirm-received"){const blocked=requireOrigin(request);if(blocked)return blocked;const order=await env.DB.prepare("SELECT status FROM sales_orders WHERE id=? AND user_id=?").bind(id,user.id).first();if(!order)return json({error:"not_found"},{status:404});if(order.status!=="SHIPPED")return json({error:"invalid_transition"},{status:409});return json({ok:true,order:await transitionOrder(env.DB,user,id,"COMPLETED")})}}
 return json({error:"not_found"},{status:404})
}

async function adminApi(request,env,url){const path=url.pathname;
 if(path==="/api/admin/session"&&request.method==="GET"){const session=await ensureUser(request,env.DB,true);if(session.denied)return json({error:"device_not_authorized",user:session.user},{status:403,headers:session.cookie?{"set-cookie":session.cookie}:{}});return json({ok:true,user:session.user},{headers:session.cookie?{"set-cookie":session.cookie}:{}})}
 const actor=await currentUser(request,env.DB);if(!actor||!ADMIN_ROLES.has(actor.role))return json({error:"unauthorized"},{status:401});
 if(path==="/api/admin/summary"&&request.method==="GET")return json({summary:await summary(env.DB)});
 if(path==="/api/admin/orders"&&request.method==="GET"){const status=clean(url.searchParams.get("status"),30),search=clean(url.searchParams.get("q"),100),conditions=[],params=[];if(status){conditions.push("status=?");params.push(status)}if(search){conditions.push("(id LIKE ? OR customer_name LIKE ? OR phone LIKE ?)");params.push(`%${search}%`,`%${search}%`,`%${search}%`)}const where=conditions.length?`WHERE ${conditions.join(" AND ")}`:"",result=await env.DB.prepare(`SELECT id,user_id,source,customer_name,phone,address,payment_method,status,subtotal,discount,shipping_fee,total,tracking_company,tracking_number,agent_code,created_at,updated_at FROM sales_orders ${where} ORDER BY created_at DESC LIMIT 300`).bind(...params).all();return json({orders:result.results.map(orderRow)})}
 if(path==="/api/admin/orders"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;try{return json({ok:true,order:await createOrder(env.DB,actor,await parseBody(request),"POS")},{status:201})}catch(error){const message=error instanceof Error?error.message:"order_failed";return json({error:message},{status:message.startsWith("insufficient_stock")?409:400})}}
 const orderMatch=path.match(/^\/api\/admin\/orders\/([^/]+)(?:\/(transition))?$/);if(orderMatch){const id=decodeURIComponent(orderMatch[1]);if(request.method==="GET"&&!orderMatch[2]){const detail=await orderDetail(env.DB,id);return detail?json({order:detail}):json({error:"not_found"},{status:404})}if(request.method==="POST"&&orderMatch[2]==="transition"){const blocked=requireOrigin(request);if(blocked)return blocked;try{const body=await parseBody(request);return json({ok:true,order:await transitionOrder(env.DB,actor,id,body.status,body)})}catch(error){const message=error instanceof Error?error.message:"transition_failed";return json({error:message},{status:message==="order_not_found"?404:409})}}}
 if(path==="/api/admin/products"&&request.method==="GET")return json({products:await listProducts(env.DB,true)});
 if(path==="/api/admin/products"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),rawId=clean(body.id,80),id=(rawId||`P-${crypto.randomUUID().slice(0,8)}`).replace(/[^A-Za-z0-9_-]/g,"-").slice(0,80),name=clean(body.name,160),category=clean(body.category,80),unit=clean(body.unit,30),price=number(body.price,0,1e8),stock=number(body.stock||0,0,1e9),images=Array.isArray(body.images)?body.images.map(x=>clean(x,1000)).filter(x=>x.startsWith("https://")).slice(0,5):[],prices=body.prices&&typeof body.prices==="object"?body.prices:{};if(!id||!name||!category||!unit||price===null||stock===null)return json({error:"invalid_product"},{status:400});try{await env.DB.prepare("INSERT INTO products(id,name,brand,category,unit,price,prices_json,stock,images_json,status) VALUES(?,?,?,?,?,?,?,?,?,'ACTIVE')").bind(id,name,clean(body.brand,80)||"JIGz",category,unit,price,JSON.stringify(prices),stock,JSON.stringify(images)).run();if(stock>0)await env.DB.prepare("INSERT INTO inventory_movements(product_id,movement_type,quantity,note) VALUES(?,'OPENING',?,'สร้างสินค้า')").bind(id,stock).run();await audit(env.DB,actor,"CREATE_PRODUCT","PRODUCT",id,{name,stock});return json({ok:true,id},{status:201})}catch(error){return json({error:String(error).includes("UNIQUE")?"product_exists":"invalid_product"},{status:409})}}
 const productMatch=path.match(/^\/api\/admin\/products\/([^/]+)$/);if(productMatch&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const id=decodeURIComponent(productMatch[1]),body=await parseBody(request),name=clean(body.name,160),category=clean(body.category,80),unit=clean(body.unit,30),price=number(body.price,0,1e8),stock=number(body.stock,0,1e9),status=clean(body.status,20).toUpperCase(),images=Array.isArray(body.images)?body.images.map(x=>clean(x,1000)).filter(x=>x.startsWith("https://")).slice(0,5):[],prices=body.prices&&typeof body.prices==="object"?body.prices:{};if(!name||!category||!unit||price===null||stock===null||!["ACTIVE","INACTIVE"].includes(status))return json({error:"invalid_product"},{status:400});await env.DB.prepare("UPDATE products SET name=?,category=?,unit=?,price=?,stock=?,status=?,images_json=?,prices_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(name,category,unit,price,stock,status,JSON.stringify(images),JSON.stringify(prices),id).run();await audit(env.DB,actor,"UPDATE_PRODUCT","PRODUCT",id,{name,stock,status});return json({ok:true})}
 if(path==="/api/admin/stock/receive"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),productId=clean(body.productId,80),quantity=number(body.quantity,0.001,1e9),unitCost=number(body.unitCost,0,1e8),supplier=clean(body.supplier,120),note=clean(body.note,300);if(!productId||quantity===null||unitCost===null)return json({error:"invalid_stock"},{status:400});const product=await env.DB.prepare("SELECT id FROM products WHERE id=?").bind(productId).first();if(!product)return json({error:"product_not_found"},{status:404});await env.DB.batch([env.DB.prepare("INSERT INTO inventory_lots(product_id,received_qty,remaining_qty,unit_cost,supplier,note) VALUES(?,?,?,?,?,?)").bind(productId,quantity,quantity,unitCost,supplier,note),env.DB.prepare("UPDATE products SET stock=COALESCE(stock,0)+?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(quantity,productId),env.DB.prepare("INSERT INTO inventory_movements(product_id,movement_type,quantity,note) VALUES(?,'RECEIVE',?,?)").bind(productId,quantity,note||supplier)]);await audit(env.DB,actor,"RECEIVE_STOCK","PRODUCT",productId,{quantity,unitCost});return json({ok:true})}
 if(path==="/api/admin/users"&&request.method==="GET"){const result=await env.DB.prepare("SELECT u.id,u.display_name,u.role,u.status,u.created_at,u.last_seen_at,p.full_name,p.phone,p.address,p.points FROM users u LEFT JOIN user_profiles p ON p.user_id=u.id ORDER BY u.last_seen_at DESC LIMIT 300").all();return json({users:result.results})}
 if(path==="/api/admin/points/adjust"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),userId=clean(body.userId,80),points=number(Math.abs(Number(body.points)),0.01,1e7),signed=Number(body.points),reason=clean(body.reason,300);if(!userId||points===null||!Number.isFinite(signed)||!reason)return json({error:"invalid_adjustment"},{status:400});const profile=await getProfile(env.DB,userId);if(Number(profile.points)+signed<0)return json({error:"insufficient_points"},{status:409});await env.DB.batch([env.DB.prepare("INSERT INTO points_ledger(user_id,type,points,reason,actor_id) VALUES(?,'ADJUST',?,?,?)").bind(userId,signed,reason,actor.id),env.DB.prepare("UPDATE user_profiles SET points=points+?,updated_at=CURRENT_TIMESTAMP WHERE user_id=?").bind(signed,userId)]);await audit(env.DB,actor,"ADJUST_POINTS","USER",userId,{points:signed,reason});return json({ok:true})}
 if(path==="/api/admin/agents"&&request.method==="GET"){const result=await env.DB.prepare("SELECT id,code,name,agent_type,commission_rate,status,created_at FROM agents ORDER BY name").all();return json({agents:result.results})}
 if(path==="/api/admin/agents"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),code=clean(body.code,24).toUpperCase(),name=clean(body.name,120),type=clean(body.agentType,20).toUpperCase(),rate=number(body.commissionRate,0,100);if(!/^[A-Z0-9-]{3,24}$/.test(code)||!name||!["RESELLER","SALES"].includes(type)||rate===null)return json({error:"invalid_agent"},{status:400});await env.DB.prepare("INSERT INTO agents(code,name,agent_type,commission_rate,status) VALUES(?,?,?,?, 'ACTIVE') ON CONFLICT(code) DO UPDATE SET name=excluded.name,agent_type=excluded.agent_type,commission_rate=excluded.commission_rate,updated_at=CURRENT_TIMESTAMP").bind(code,name,type,rate).run();await audit(env.DB,actor,"UPSERT_AGENT","AGENT",code,{name,type,rate});return json({ok:true})}
 if(path==="/api/admin/commissions"&&request.method==="GET"){const result=await env.DB.prepare("SELECT c.id,c.order_id,a.code agent_code,a.name agent_name,c.revenue_net,c.actual_cost,c.deductions,c.profit_base,c.commission_rate,c.commission_amount,c.status,c.created_at FROM sales_commissions c JOIN agents a ON a.id=c.agent_id ORDER BY c.created_at DESC LIMIT 300").all();return json({commissions:result.results})}
 if(path==="/api/admin/commissions/recalculate"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),id=clean(body.orderId,80),commission=await recalculateCommission(env.DB,id);return commission?json({ok:true,commission}):json({error:"order_or_agent_not_found"},{status:404})}
 if(path==="/api/admin/promotions"&&request.method==="GET"){const result=await env.DB.prepare("SELECT * FROM promotions ORDER BY created_at DESC LIMIT 200").all();return json({promotions:result.results})}
 if(path==="/api/admin/promotions"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),title=clean(body.title,160),description=clean(body.description,500),type=clean(body.discountType,20).toUpperCase(),value=number(body.discountValue||0,0,1e8),status=clean(body.status||"ACTIVE",20).toUpperCase();if(!title||!["INFO","PERCENT","AMOUNT"].includes(type)||value===null||!["ACTIVE","INACTIVE"].includes(status))return json({error:"invalid_promotion"},{status:400});await env.DB.prepare("INSERT INTO promotions(title,description,discount_type,discount_value,status,starts_at,ends_at) VALUES(?,?,?,?,?,?,?)").bind(title,description,type,value,status,clean(body.startsAt,30)||null,clean(body.endsAt,30)||null).run();await audit(env.DB,actor,"CREATE_PROMOTION","PROMOTION",null,{title,type,value});return json({ok:true})}
 if(path==="/api/admin/settings"&&request.method==="GET")return json({settings:await settings(env.DB,false)});
 if(path==="/api/admin/settings"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),allowed=["shop_name","announcement","shop_open","shipping_fee","line_oa","instagram","bank_name","bank_account","bank_number","qr_image","theme","points_rate"],entries=Object.entries(body).filter(([key])=>allowed.includes(key)).map(([key,value])=>[key,clean(value,key==="qr_image"?650000:1000)]);if(!entries.length)return json({error:"empty_settings"},{status:400});await env.DB.batch(entries.map(([key,value])=>env.DB.prepare("INSERT INTO system_settings(setting_key,setting_value,updated_at) VALUES(?,?,CURRENT_TIMESTAMP) ON CONFLICT(setting_key) DO UPDATE SET setting_value=excluded.setting_value,updated_at=CURRENT_TIMESTAMP").bind(key,value)));await audit(env.DB,actor,"UPDATE_SETTINGS","SYSTEM",null,{keys:entries.map(([key])=>key)});return json({ok:true,settings:await settings(env.DB,false)})}
 if(path==="/api/admin/chat"&&request.method==="GET"){const after=Math.max(0,Number(url.searchParams.get("after")||0)),result=await env.DB.prepare("SELECT id,user_id,display_name,message,created_at FROM chat_messages WHERE id>? ORDER BY id DESC LIMIT 100").bind(after).all();return json({messages:result.results.reverse()})}
 if(path==="/api/admin/chat"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),message=clean(body.message,1000);if(!message)return json({error:"empty_message"},{status:400});await env.DB.prepare("INSERT INTO chat_messages(user_id,display_name,message) VALUES(?,?,?)").bind(actor.id,actor.display_name,message).run();return json({ok:true})}
 if(path==="/api/admin/reports"&&request.method==="GET"){const [totals,statuses,days,top,stock,auditRows]=await env.DB.batch([env.DB.prepare("SELECT COUNT(*) orders,COALESCE(SUM(CASE WHEN status<>'CANCELLED' THEN total ELSE 0 END),0) revenue,COALESCE(SUM(CASE WHEN status<>'CANCELLED' THEN (SELECT SUM(actual_cost) FROM sales_order_items i WHERE i.order_id=sales_orders.id) ELSE 0 END),0) cost FROM sales_orders"),env.DB.prepare("SELECT status,COUNT(*) total,COALESCE(SUM(total),0) amount FROM sales_orders GROUP BY status ORDER BY total DESC"),env.DB.prepare("SELECT date(created_at) day,COUNT(*) orders,COALESCE(SUM(total),0) revenue FROM sales_orders WHERE created_at>=datetime('now','-30 days') AND status<>'CANCELLED' GROUP BY date(created_at) ORDER BY day"),env.DB.prepare("SELECT product_id,product_name,SUM(quantity) quantity,SUM(line_total) revenue FROM sales_order_items i JOIN sales_orders o ON o.id=i.order_id WHERE o.status<>'CANCELLED' GROUP BY product_id,product_name ORDER BY revenue DESC LIMIT 10"),env.DB.prepare("SELECT id,name,category,unit,stock,status FROM products ORDER BY COALESCE(stock,0) ASC LIMIT 50"),env.DB.prepare("SELECT id,actor_id,action,entity_type,entity_id,details_json,created_at FROM audit_logs ORDER BY id DESC LIMIT 100")]);const base=totals.results[0]||{},revenue=Number(base.revenue||0),cost=Number(base.cost||0);return json({totals:{orders:Number(base.orders||0),revenue,cost,profit:revenue-cost},statuses:statuses.results,days:days.results,topProducts:top.results,stock:stock.results,audit:auditRows.results})}
 if(path==="/api/admin/push/config"&&request.method==="GET"){const keys=await ensureVapidKeys(env.DB),row=await env.DB.prepare("SELECT COUNT(*) total FROM push_subscriptions WHERE user_id=? AND status='ACTIVE'").bind(actor.id).first();return json({supported:true,publicKey:keys.publicKey,subscriptions:Number(row?.total||0)})}
 if(path==="/api/admin/push/subscribe"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const body=await parseBody(request),subscription=body?.subscription,endpoint=clean(subscription?.endpoint,2048);if(!endpoint.startsWith("https://")||!subscription?.keys?.p256dh||!subscription?.keys?.auth)return json({error:"invalid_subscription"},{status:400});await env.DB.prepare("INSERT INTO push_subscriptions(user_id,endpoint,subscription_json,status) VALUES(?,?,?,'ACTIVE') ON CONFLICT(endpoint) DO UPDATE SET user_id=excluded.user_id,subscription_json=excluded.subscription_json,status='ACTIVE',updated_at=CURRENT_TIMESTAMP").bind(actor.id,endpoint,JSON.stringify(subscription)).run();return json({ok:true})}
 if(path==="/api/admin/push/test"&&request.method==="POST"){const blocked=requireOrigin(request);if(blocked)return blocked;const rows=await env.DB.prepare("SELECT id,endpoint FROM push_subscriptions WHERE user_id=? AND status='ACTIVE' ORDER BY updated_at DESC LIMIT 10").bind(actor.id).all();if(!rows.results.length)return json({error:"no_subscription"},{status:404});const keys=await ensureVapidKeys(env.DB),results=await Promise.all(rows.results.map(async row=>({id:row.id,...await sendPush(row.endpoint,keys)}))),expired=results.filter(item=>item.expired);if(expired.length)await env.DB.batch(expired.map(item=>env.DB.prepare("UPDATE push_subscriptions SET status='EXPIRED',updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(item.id)));return json({ok:results.some(item=>item.ok),sent:results.filter(item=>item.ok).length,failed:results.filter(item=>!item.ok).length},{status:results.some(item=>item.ok)?200:502})}
 return json({error:"not_found"},{status:404})
}

export default{async fetch(request,env,ctx){const url=new URL(request.url);try{
 if(request.method==="GET"&&url.pathname==="/api/health"){await initializeDatabase(env.DB);await env.DB.prepare("SELECT 1").first();return json({ok:true,database:"connected",version:"4.0.0"})}
 if(url.pathname==="/api/admin/session"||url.pathname.startsWith("/api/admin/")){await initializeDatabase(env.DB);return adminApi(request,env,url)}
 if(url.pathname.startsWith("/api/")){const session=await ensureUser(request,env.DB,false);if(url.pathname==="/api/session"&&request.method==="GET")return json({user:session.user,profile:await getProfile(env.DB,session.user.id)},{headers:session.cookie?{"set-cookie":session.cookie}:{}});const response=await publicApi(request,env,url,session.user,ctx);if(session.cookie){const headers=new Headers(response.headers);headers.append("set-cookie",session.cookie);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}return response}
 if(url.pathname==="/admin"||url.pathname.startsWith("/admin/")){const target=new URL("/admin.html",url);return env.ASSETS.fetch(new Request(target,request))}
 return env.ASSETS.fetch(request)
 }catch(error){console.error(JSON.stringify({event:"request_failed",path:url.pathname,message:error instanceof Error?error.message:String(error)}));const message=error instanceof Error&&["invalid_content_type","payload_too_large"].includes(error.message)?error.message:"service_unavailable";return json({error:message},{status:message==="service_unavailable"?503:400})}}};
